/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ibvnYMOAYpX
 */


export function ImageGrid() {
  return (
    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
      <div className="relative group overflow-hidden rounded-lg">
        <img
          alt="Image 1"
          className="object-cover w-full h-60"
          height={300}
          src="/placeholder.svg"
          style={{
            aspectRatio: "400/300",
            objectFit: "cover",
          }}
          width={400}
        />
        <div className="bg-gray-100 p-4 dark:bg-gray-800">
          <h3 className="font-semibold text-sm">Tranquil Forest</h3>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <img
          alt="Image 2"
          className="object-cover w-full h-60"
          height={300}
          src="/images/A1/Unit-1/before-after.png"
          style={{
            aspectRatio: "400/300",
            objectFit: "cover",
          }}
          width={400}
        />
        <div className="bg-gray-100 p-4 dark:bg-gray-800">
          <h3 className="font-semibold text-sm">Sunny Beach</h3>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <img
          alt="Image 3"
          className="object-cover w-full h-60"
          height={300}
          src="/placeholder.svg"
          style={{
            aspectRatio: "400/300",
            objectFit: "cover",
          }}
          width={400}
        />
        <div className="bg-gray-100 p-4 dark:bg-gray-800">
          <h3 className="font-semibold text-sm">Snowy Peaks</h3>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <img
          alt="Image 4"
          className="object-cover w-full h-60"
          height={300}
          src="/placeholder.svg"
          style={{
            aspectRatio: "400/300",
            objectFit: "cover",
          }}
          width={400}
        />
        <div className="bg-gray-100 p-4 dark:bg-gray-800">
          <h3 className="font-semibold text-sm">Vibrant City</h3>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <img
          alt="Image 5"
          className="object-cover w-full h-60"
          height={300}
          src="/placeholder.svg"
          style={{
            aspectRatio: "400/300",
            objectFit: "cover",
          }}
          width={400}
        />
        <div className="bg-gray-100 p-4 dark:bg-gray-800">
          <h3 className="font-semibold text-sm">Serene Lake</h3>
        </div>
      </div>
      <div className="relative group overflow-hidden rounded-lg">
        <img
          alt="Image 6"
          className="object-cover w-full h-60"
          height={300}
          src="/placeholder.svg"
          style={{
            aspectRatio: "400/300",
            objectFit: "cover",
          }}
          width={400}
        />
        <div className="bg-gray-100 p-4 dark:bg-gray-800">
          <h3 className="font-semibold text-sm">Golden Hour</h3>
        </div>
      </div>
    </div>
  )
}
